# Generated by Django 5.0 on 2024-01-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_category_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMPTT',
        ),
    ]
