# Generated by Django 5.0 on 2024-01-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_categorymptt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
