# Generated by Django 5.0 on 2024-01-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
