# Generated by Django 5.0 on 2024-01-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_rating_star_remove_rating_ip_delete_ratingstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Star Value',
                'verbose_name_plural': 'Star Value',
                'ordering': ['-value'],
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='ip',
            field=models.CharField(default=1, max_length=15, verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ratingstar', verbose_name='star'),
        ),
    ]
